spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: ${DHI_CONNECTION_STRING}
    username: ${DHI_CONNECTION_USERNAME}
    password: ${DHI_CONNECTION_PASSWORD}
